# Generated by Django 3.2.3 on 2021-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_analysis', models.DateTimeField(auto_now_add=True)),
                ('harmless', models.BooleanField(null=True)),
                ('malicious', models.BooleanField(null=True)),
                ('suspicious', models.BooleanField(null=True)),
                ('hash_obj', models.CharField(max_length=200, null=True)),
                ('antiviruses_results', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'vt_analysis',
                'ordering': ['-date_time_analysis'],
            },
        ),
        migrations.AddIndex(
            model_name='vtanalysis',
            index=models.Index(fields=['hash_obj'], name='hash_obj_idx'),
        ),
    ]
